print("hello\nworld")
print("hello\tworld")                        
print("hello\rworld")  
print("AAA\bBBB") 
print("To,\fThe headmaster") 
print("he\\his")
print("she\\her")
print("they\\them")
print("he\ahis")
print("she\aher")
print("they\athem") 
print('it\'s her choice') 
#this is test
print('it\'s her choice')                  